//@ui5-bundle pritesh/fiori/zmyprofilepwa/Component-preload.js
jQuery.sap.registerPreloadedModules({
"version":"2.0",
"modules":{
	"pritesh/fiori/zmyprofilepwa/Component.js":function(){sap.ui.define(["sap/ui/core/UIComponent","sap/ui/Device","pritesh/fiori/zmyprofilepwa/model/models"],function(e,i,t){"use strict";return e.extend("pritesh.fiori.zmyprofilepwa.Component",{metadata:{manifest:"json"},init:function(){e.prototype.init.apply(this,arguments);this.getRouter().initialize();this.setModel(t.createDeviceModel(),"device")}})});
},
	"pritesh/fiori/zmyprofilepwa/controller/Main.controller.js":function(){sap.ui.define(["sap/ui/core/mvc/Controller"],function(e){"use strict";return e.extend("pritesh.fiori.zmyprofilepwa.controller.Main",{onInit:function(){document.getElementById("splash-screen").remove()},onPress:function(){sap.m.MessageToast.show("Pressed")}})});
},
	"pritesh/fiori/zmyprofilepwa/i18n/i18n.properties":'title=My Career Profile (Created with OpenUI5)\nappTitle=Pritesh Patel\nappDescription=Pritesh Patel - SAP Developer Profile',
	"pritesh/fiori/zmyprofilepwa/i18n/i18n_en.properties":'title=My Career Profile (Created with OpenUI5)\nappTitle=Pritesh Patel\nappDescription=Pritesh Patel - SAP Developer Profile',
	"pritesh/fiori/zmyprofilepwa/i18n/i18n_en_US.properties":'title=My Career Profile (Created with OpenUI5)\nappTitle=Pritesh Patel\nappDescription=Pritesh Patel - SAP Developer Profile',
	"pritesh/fiori/zmyprofilepwa/localService/mockserver.js":function(){sap.ui.define(["sap/ui/core/util/MockServer","sap/ui/model/json/JSONModel","sap/base/util/UriParameters","sap/base/Log"],function(e,r,t,a){"use strict";var o,i="pritesh.fiori.zmyprofilepwa/",n=i+"localService/mockdata";var s={init:function(s){var u=s||{};return new Promise(function(s,c){var p=sap.ui.require.toUrl(i+"manifest.json"),f=new r(p);f.attachRequestCompleted(function(){var r=new t(window.location.href),c=sap.ui.require.toUrl(n),p=f.getProperty("/sap.app/dataSources/mainService"),l=sap.ui.require.toUrl(i+p.settings.localUri),d=p.uri&&new URI(p.uri).absoluteTo(sap.ui.require.toUrl(i)).toString();if(!o){o=new e({rootUri:d})}else{o.stop()}e.config({autoRespond:true,autoRespondAfter:u.delay||r.get("serverDelay")||500});o.simulate(l,{sMockdataBaseUrl:c,bGenerateMissingMockData:true});var m=o.getRequests();var v=function(e,r,t){t.response=function(t){t.respond(e,{"Content-Type":"text/plain;charset=utf-8"},r)}};if(u.metadataError||r.get("metadataError")){m.forEach(function(e){if(e.path.toString().indexOf("$metadata")>-1){v(500,"metadata Error",e)}})}var g=u.errorType||r.get("errorType"),h=g==="badRequest"?400:500;if(g){m.forEach(function(e){v(h,g,e)})}o.setRequests(m);o.start();a.info("Running the app with mock data");s()});f.attachRequestFailed(function(){var e="Failed to load application manifest";a.error(e);c(new Error(e))})})},getMockServer:function(){return o}};return s});
},
	"pritesh/fiori/zmyprofilepwa/manifest.json":'{"name":"Pritesh Patel Profile","short_name":"Pritesh-Profile","icons":[{"src":"icons/icon-128x128.png","sizes":"128x128","type":"image/png"},{"src":"icons/icon-144x144.png","sizes":"144x144","type":"image/png"},{"src":"icons/icon-152x152.png","sizes":"152x152","type":"image/png"},{"src":"icons/icon-192x192.png","sizes":"192x192","type":"image/png"},{"src":"icons/icon-256x256.png","sizes":"256x256","type":"image/png"},{"src":"icons/icon-512x512.png","sizes":"512x512","type":"image/png"}],"start_url":"index.html","display":"standalone","background_color":"#244C7C","theme_color":"#FFFFFF","_version":"1.32.0","sap.app":{"id":"pritesh.fiori.zmyprofilepwa","type":"application","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"title":"{{appTitle}}","description":"{{appDescription}}","resources":"resources.json","ach":"ach"},"sap.ui":{"technology":"UI5","icons":{"icon":"sap-icon://task","favIcon":"","phone":"","phone@2":"","tablet":"","tablet@2":""},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"flexEnabled":false,"rootView":{"viewName":"pritesh.fiori.zmyprofilepwa.view.Main","type":"XML","async":true,"id":"Main"},"dependencies":{"minUI5Version":"1.104.1","libs":{"sap.ui.core":{},"sap.m":{},"sap.ui.layout":{}}},"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"pritesh.fiori.zmyprofilepwa.i18n.i18n"}}},"resources":{"css":[{"uri":"css/style.css"}]},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","async":true,"viewPath":"pritesh.fiori.zmyprofilepwa.view","controlAggregation":"pages","controlId":"app","clearControlAggregation":false},"routes":[{"name":"RouteMain","pattern":"RouteMain","target":["TargetMain"]}],"targets":{"TargetMain":{"viewType":"XML","transition":"slide","clearControlAggregation":false,"viewId":"Main","viewName":"Main"}}}}}',
	"pritesh/fiori/zmyprofilepwa/model/models.js":function(){sap.ui.define(["sap/ui/model/json/JSONModel","sap/ui/Device"],function(e,n){"use strict";return{createDeviceModel:function(){var i=new e(n);i.setDefaultBindingMode("OneWay");return i}}});
},
	"pritesh/fiori/zmyprofilepwa/register-worker.js":function(){if("serviceWorker"in navigator){navigator.serviceWorker.register("./service-worker.js").then(function(){console.log("Service Worker Registered")})}
},
	"pritesh/fiori/zmyprofilepwa/service-worker.js":'const CACHE_NAME="pwa-ui5-priteshprofile-v1.0.3";const RESOURCES_TO_PRELOAD=["index.html","logo.svg","register-worker.js","view/","controller/","css/style.css","i18n/","icons/","img/","Component.js","Component-preload.js","favicon.ico","manifest.json"];const cdnBase="https://openui5.hana.ondemand.com/resources/";const resourcesToCache=RESOURCES_TO_PRELOAD.concat([`${cdnBase}sap-ui-core.js`,`${cdnBase}sap/ui/core/library-preload.js`,`${cdnBase}sap/ui/core/themes/sap_fiori_3/library.css`,`${cdnBase}sap/ui/core/themes/base/fonts/SAP-icons.woff2`,`${cdnBase}sap/m/library-preload.js`,`${cdnBase}sap/m/themes/sap_fiori_3/library.css`]);self.addEventListener("install",function(e){self.skipWaiting();e.waitUntil(caches.open(CACHE_NAME).then(function(e){return e.addAll(RESOURCES_TO_PRELOAD)}).catch(function(e){console.error(e)}))});self.addEventListener("activate",function(e){e.waitUntil(caches.keys().then(function(e){return Promise.all(e.map(function(e){if(e!==CACHE_NAME){return caches.delete(e)}}))}))});self.addEventListener("fetch",function(e){if(e.request.method==="GET"){e.respondWith(caches.match(e.request).then(function(n){if(n){return n}let s=e.request.clone();return fetch(s).then(function(n){if(n.type==="opaque"){return n}else if(!n.ok){console.error(n.statusText)}else{return caches.open(CACHE_NAME).then(function(s){s.put(e.request,n.clone());return n}).catch(function(e){console.error(e);return e})}}).catch(function(e){console.error(e);return caches.match("offline-404.html")})}))}});',
	"pritesh/fiori/zmyprofilepwa/view/Main.view.xml":'<mvc:View\n    controllerName="pritesh.fiori.zmyprofilepwa.controller.Main"\n    xmlns:mvc="sap.ui.core.mvc"    \n    xmlns="sap.m"\n><Shell id="shell"><App id="app"><pages><Page id="page" title="{i18n>title}"><content><HBox><VBox height="20%"><Image class="sapUiTinyMargin myImage" src="./img/ProfilePic.jpg" height="165px"/></VBox><SlideTile class="sapUiTinyMargin tileLayout"><tiles><GenericTile frameType="TwoByOne" state="Loaded" header="Welcome"><TileContent footer=""><FeedContent contentText="Here you will find information about me and my work."/></TileContent></GenericTile><GenericTile frameType="TwoByOne" state="Loaded" header="Pritesh Patel"><TileContent footer="Residing in Illinois"><NewsContent contentText="" subheader="(657) 238-9455"/></TileContent></GenericTile></tiles></SlideTile></HBox><Panel class="sapUiLargeMarginTop" expandable="false" expand="true" headerText="My Portfolio"><HBox><GenericTile class="sapUiMediumMarginBegin sapUiTinyMarginTop tileLayout" header="My Projects" press="press"/><GenericTile class="sapUiMediumMarginBegin sapUiTinyMarginTop tileLayout" header="Work History" press="press"/><GenericTile class="sapUiMediumMarginBegin sapUiTinyMarginTop tileLayout" header="About Me" press="press"/></HBox></Panel></content></Page></pages></App></Shell></mvc:View>\n'
}});
